### ISSUE TITLE
Add novigation buttons between pending and processed requests

### ISSUE THREAD

**Issue by altzii** [levzakharov/itis-webapp#101]
Добавить роутинг для 2-х страниц сотрудников деканата

/certificates/processed
![2017-05-28 12 40 08](https://cloud.githubusercontent.com/assets/13038545/26527739/e9e19a16-43a2-11e7-920c-dcde956cce8e.png)
/certificates/
![2017-05-28 12 40 28](https://cloud.githubusercontent.com/assets/13038545/26527740/e9e55ac0-43a2-11e7-8b46-32cae0e38a77.png)

**Comment by GatinMI** [comment]
Все не по тз, не буду делать!! @altzii
