### ISSUE TITLE
FIx authorization (whitelabel error page)

### ISSUE THREAD

**Issue by SkywalkerFox** [levzakharov/itis-webapp#106]
Иногда при авторизации, чаще всего при самой первой попытке, выходит вот это
![default](https://cloud.githubusercontent.com/assets/13809640/26530672/225f3ad0-43e2-11e7-8458-2ae0031f24f3.png)

**Comment by Khakov** [comment]
можно подробнее, никогда такого не вылазило

**Comment by SkywalkerFox** [comment]
Запуск приложения, самая первая попытка входа. Входные данные корректны. Если вернуться на страницу логина и еще раз попытаться войти, то все норм. При попытке обновить страницу с ошибкой ничего не меняется.
Такое появилось именно в этой версии.

**Comment by GatinMI** [comment]
Компьютер поменяй, у тебя барахлит

**Comment by SkywalkerFox** [comment]
Лишь бы у вас руки не кривые были с:
