### ISSUE TITLE
Certificates integer bug

### ISSUE THREAD

**Issue by dre0dru** [levzakharov/itis-webapp#108]
1. Авторизоваться под студентом/старостой
2. Перейти в "Запросы в деканат"
3. Если в поле "Запросить справку об учебе в количестве" ввести число больше int (больше 2 147 483 647) и сделать запрос, вылезает следующее:
![image](https://cloud.githubusercontent.com/assets/17127480/26530746/9319d658-43e3-11e7-94ed-dd814f879cd2.png)

**Comment by Khakov** [comment]
#113

**Comment by altzii** [comment]
#132
