### ISSUE TITLE
Schedule bug

### ISSUE THREAD

**Issue by dre0dru** [levzakharov/itis-webapp#124]
1 Зайти под студентом 401 группы
2 Открыть расписание
3 Выбрать "Неделя" и "Общий", нажать "Изменить"
4 Выбрать "День" и "Общий", нажать "Изменить", вылетит следующий эксепшн:
![image](https://cloud.githubusercontent.com/assets/17127480/26543713/9ee88a72-4467-11e7-8170-c3a7e639f5e1.png)

**Comment by GatinMI** [comment]
проверь, пожалуйста, после пула
