### ISSUE TITLE
Неправильное время уведомлений 

### ISSUE THREAD

**Issue by anisimovajulia** [levzakharov/itis-webapp#162]
![image](https://cloud.githubusercontent.com/assets/13524828/26676346/054e4fee-46d0-11e7-9efa-b3a530e2aaa2.png)

Зайти под деканатом.
Создать уведомление.
Зайти в отправленные и посмотреть последние уведомления.
Время отправления уведомления отстает на 3 часа от правильного

**Comment by GoodBoy962** [comment]
думаю надо на серваке время поменять

**Comment by altzii** [comment]
@GoodBoy962 +

**Comment by GoodBoy962** [comment]
@anisimovajulia поменял время на серваке, посмотри еще раз. Если ок, закрой issue
