### ISSUE TITLE
Нет валидации на верхнюю границу справок во фронте

### ISSUE THREAD

**Issue by anisimovajulia** [levzakharov/itis-webapp#163]
Зайти под студентом.
перейти в запрос в деканат.
Накликать 25 справок,нажать запросить
Проблема: не должно быть даже возможности кликать больше 20 справок,если таковая граница(должно быть как с 0)
![image](https://cloud.githubusercontent.com/assets/13524828/26676463/95d499e2-46d0-11e7-8a75-d31282d68570.png)

**Comment by altzii** [comment]
#165
