### ISSUE TITLE
Отправляется сразу 4 сообщения!

### ISSUE THREAD

**Issue by anisimovajulia** [levzakharov/itis-webapp#164]
Зайти под деканатом
перейти в чат
выбрать получается
отправить сообщение
отправляетя сразу 4 копии сообщения:
![image](https://cloud.githubusercontent.com/assets/13524828/26676672/6ef4cad0-46d1-11e7-96a4-a80dc26a069f.png)

**Comment by altzii** [comment]
При нажатии на 'Enter'

**Comment by altzii** [comment]
#166
