### ISSUE TITLE
Create db

### ISSUE THREAD

**Issue by levzakharov** [levzakharov/itis-webapp#5]
Создать и настроить базу данных.

БД - PostgreSQL 9.6.2
ORM - Hibernate 4
Управление миграциями БД - Liquibase

**Comment by GoodBoy962** [comment]
чекайте

**Comment by GoodBoy962** [comment]
@levzakharov @altzii @Khakov @GatinMI @denmkr 
от этой задачи зависят остальные. Мержайте быстрее) 
https://github.com/levzakharov/itis-webapp/pull/8
