### ISSUE TITLE
Add docker containers

### ISSUE THREAD

**Issue by levzakharov** [levzakharov/itis-webapp#52]
Подготовить docker контейнеры для запуска приложения и базы данных.

Предлагаю завести и связать следующие контейнеры:

1. Контейнер для веб-приложения (Можно использовать этот [образ](https://hub.docker.com/_/maven/))
2. Контейнер для базы данных (Я у себя разворачивал на основе этого [образа](https://hub.docker.com/_/postgres/))

Пишите в комментариях свои мысли.

**Comment by altzii** [comment]
Лев, сделай ты это :)

**Comment by Khakov** [comment]
поддерживаю бунт)

**Comment by levzakharov** [comment]
Ограничился контейнером для базы данных. Само приложение собирается и запускается прямо на машине.

**Comment by altzii** [comment]
Good job!
