### ISSUE TITLE
Add certificates

### ISSUE THREAD

**Issue by levzakharov** [levzakharov/itis-webapp#55]
Добавить поддержку работы со справками от деканата.

Задачи:

- Реализации функции запроса справки
- Реализации функции просмотра истории запросов
- Реализация функции генерации справки

Верстку брать отсюда #56

**Comment by GoodBoy962** [comment]
с генерацией хотелось бы поподробнее. На данный момент в базе есть поле text. Оно стринговое. Наверное в результате должен возвращаться документ или нет?

**Comment by altzii** [comment]
#98

**Comment by altzii** [comment]
DONE
