### ISSUE TITLE
Create db schema

### ISSUE THREAD

**Issue by levzakharov** [levzakharov/itis-webapp#6]
Создать схему базы данных.

Схема БД:

![Схема БД](https://cloud.githubusercontent.com/assets/10602847/25243813/0e132ba2-2607-11e7-8acc-09fdbf35043c.jpg)

**Comment by altzii** [comment]
User и Role лучше сразу через "многие-ко-многим" сделать, а то может получиться так, что у пользователя одновременно несколько ролей будет.

**Comment by GoodBoy962** [comment]
а кто на это должен миграции накатить?

**Comment by altzii** [comment]
#9

**Comment by GoodBoy962** [comment]
@altzii , я миграцию для ролей сделал. Обновил README

**Comment by altzii** [comment]
Создали миграции, проверьте

#14
